/** Standalone review uses actual React page/components; only Next routing/assets are adapted. */
import {build} from 'esbuild';
import {readFileSync,writeFileSync,readdirSync,mkdirSync} from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const dest=process.argv[2]||'/tmp/rinan-cis-v2-preview.html';
const images={};
for(const name of ['rinan-station','rinan-station-front'])for(const w of [480,800,1200]){const f=`/images/optimized/${name}-${w}.webp`;images[f]='data:image/webp;base64,'+readFileSync('public'+f).toString('base64');}
for(const name of ['rinan-station','rinan-station-front'])images[`/images/${name}.jpg`]=images[`/images/optimized/${name}-800.webp`];
images['/partners/rinan-commons.jpg']='data:image/jpeg;base64,'+readFileSync('public/partners/rinan-commons.jpg').toString('base64');
const bundle=await build({entryPoints:['review/entry.tsx'],bundle:true,write:false,minify:true,jsx:'automatic',define:{'process.env.NODE_ENV':'"production"'},plugins:[{name:'review-adapter',setup(b){
 b.onResolve({filter:/^next\/link$/},()=>({path:path.join(root,'review/link.tsx')}));
 b.onResolve({filter:/^next\/navigation$/},()=>({path:'navigation',namespace:'preview'}));
 b.onLoad({filter:/.*/,namespace:'preview'},()=>({contents:'export function notFound(){throw new Error("Unknown story")}',loader:'js'}));
 b.onLoad({filter:/app\/site-path\.ts$/},()=>({contents:`const assets=${JSON.stringify(images)};export function sitePath(path){return assets[path]||(path==='/maps/'?'https://jimmy10107.github.io/rinan-commons/maps/':'/rinan-commons'+path)}`,loader:'js'}));
}}]});
const cssLinks=[...readFileSync('out/index.html','utf8').matchAll(/<link[^>]*href="([^"]+\.css)"[^>]*>/g)].map(m=>m[1]);
let css=cssLinks.map(url=>readFileSync(path.join(root,'out',url.replace('/rinan-commons/','')),'utf8')).join('\n');
css=css.replace(/url\(([^)]+\.woff2)\)/g,(match,url)=>{url=url.replace(/[\"']/g,'');let file=url.startsWith('/rinan-commons/')?path.join(root,'out',url.slice('/rinan-commons/'.length)):path.resolve(root,'out/_next/static/chunks',url);return 'url(data:font/woff2;base64,'+readFileSync(file).toString('base64')+')';});
const inner='<!doctype html><html lang="zh-Hant"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><style>'+css+'</style></head><body><div id="app"></div><script>'+bundle.outputFiles[0].text.replaceAll('</script','<\\/script')+'</script></body></html>';
const data=JSON.stringify(inner).replaceAll('<','\\u003c');
const fontRules=(css.match(/@font-face\{[^}]+\}/g)||[]).join('');
const html=`<!doctype html><html lang="zh-Hant"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>日南稻站｜CIS 第二版互動預覽</title><style>${fontRules}*{box-sizing:border-box}body{margin:0;background:#e6e6e2;color:#231f20;font:14px/1.6 'Rinan Sans',system-ui,'Microsoft JhengHei',sans-serif}header{padding:12px 20px;background:white;border-bottom:1px solid #ddd;display:flex;align-items:center;gap:12px;flex-wrap:wrap}header strong{margin-right:auto}select,button{font:inherit;min-height:40px;background:white;border:1px solid #bbc2c8;border-radius:4px;padding:6px 12px;color:#231f20}button[aria-pressed=true]{background:#456c90;color:white}main{display:flex;justify-content:center;padding:16px 0}iframe{display:block;border:0;background:white;width:100%;height:calc(100dvh - 136px);min-height:440px;box-shadow:0 0 0 1px #d7d7d2}p{margin:0;padding:7px 20px;font-size:12px;color:#565856}a{color:#456c90}@media(max-width:650px){header{padding:10px 12px;gap:8px}header strong{width:100%}main{padding:0}iframe{height:calc(100dvh - 182px)}p{padding:8px 12px}}</style></head><body><header><strong>日南稻站 · CIS 第二版 <small>未發布</small></strong><label>頁面 <select id="route"><option value="/">首頁</option><option value="/about/">關於稻站</option><option value="/stories/">地方筆記</option><option value="/explore/">九里地圖</option><option value="/visit/">到訪交通</option><option value="/stories/a-station-in-daily-life/">車站筆記</option><option value="/stories/a-place-to-stop/">空間筆記</option></select></label><button data-width="100%" aria-pressed="true">桌機</button><button data-width="390px" aria-pressed="false">手機 390</button><button data-width="320px" aria-pressed="false">窄螢幕 320</button></header><p>可操作選單、搜尋與頁面。地圖需連網；活動與展覽連至既有網站。原 Logo 沿用，已內嵌品牌中文字體。下載後以瀏覽器開啟。</p><main><iframe id="preview" title="日南稻站互動預覽"></iframe></main><script>const frame=document.getElementById('preview');frame.srcdoc=${data};const select=document.getElementById('route');select.onchange=()=>frame.contentWindow.postMessage({type:'rinan-go',path:select.value},'*');document.querySelectorAll('[data-width]').forEach(b=>b.onclick=()=>{frame.style.width=b.dataset.width;frame.style.maxWidth='100%';document.querySelectorAll('[data-width]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))});window.addEventListener('message',e=>{if(e.source===frame.contentWindow&&e.data?.type==='rinan-route')select.value=e.data.path});</script></body></html>`;
mkdirSync(path.dirname(dest),{recursive:true});writeFileSync(dest,html);console.log(JSON.stringify({file:dest,bytes:Buffer.byteLength(html),pages:7,mode:'Actual React components; Next routing adapted for local-file preview'}));
